name: Test Docsible PR and Generate Documentation

on:
  workflow_dispatch:
    inputs:
      docsible_pr_number:
        description: "Optional: Pull request number on docsible/docsible"
        required: false
        type: number
      use_latest:
        description: "Use latest main branch from docsible/docsible instead of a PR?"
        required: false
        default: false
        type: boolean

permissions:
  contents: write

jobs:
  test_docsible:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - name: Show current branch
        run: echo "🟢 Running on branch - ${{ github.ref_name }}"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Clone and install Docsible from PR or latest
        run: |
          mkdir -p deps
          cd deps
          if [[ "${{ github.event.inputs.use_latest }}" == "true" ]]; then
            echo "📦 Cloning latest Docsible from main"
            git clone https://github.com/docsible/docsible.git
            cd docsible
            git checkout main
          elif [[ -n "${{ github.event.inputs.docsible_pr_number }}" ]]; then
            echo "📦 Fetching PR #${{ github.event.inputs.docsible_pr_number }}"
            git clone https://github.com/docsible/docsible.git
            cd docsible
            git fetch origin pull/${{ github.event.inputs.docsible_pr_number }}/head:pr-${{ github.event.inputs.docsible_pr_number }}
            git checkout pr-${{ github.event.inputs.docsible_pr_number }}
          else
            echo "❌ Provide a PR number or enable 'use_latest'."
            exit 1
          fi

          echo "✅ Commit: $(git rev-parse --short HEAD) - $(git log -1 --pretty=%s)"
          echo "commit=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "message=$(git log -1 --pretty=%s)" >> $GITHUB_ENV

          pip install .

      - name: Get Docsible version
        id: docsible_info
        run: |
          VERSION=$(docsible --version | sed -E 's/.*version ([0-9.]+)/\1/')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "commit=${{ env.commit }}" >> $GITHUB_OUTPUT
          echo "message=${{ env.message }}" >> $GITHUB_OUTPUT

      - name: Generate documentation for role
        run: |
          docsible -r ./ -g -o README.md -com -nob

      - name: Check for documentation changes
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md

          if git diff --cached --exit-code; then
            echo "✅ No documentation changes to commit"
          elif [ -n "${TOKEN}" ]; then
            COMMIT_MSG="📘 update using docsible v${{ steps.docsible_info.outputs.version }}"
            COMMIT_MSG+=" (commit: ${{ steps.docsible_info.outputs.commit }})"
            COMMIT_MSG+=" - ${{ steps.docsible_info.outputs.message }}"
            git commit -m "${COMMIT_MSG}"
            BRANCH_NAME="main"
            echo "🔁 Pushing changes back to branch: ${BRANCH_NAME}"
            git push "https://${TOKEN}@github.com/docsible/sysinspect.git" HEAD:${BRANCH_NAME}
          else
            echo "⚠️ Skipping push: TOKEN is not set"
          fi

