name: Test Docsible PR and Generate Documentation

on:
  workflow_dispatch:
    inputs:
      docsible_pr_number:
        description: "Optional: Pull request number on docsible/docsible"
        required: false
        type: number
      use_latest:
        description: "Use latest main branch from docsible/docsible instead of a PR?"
        required: false
        default: false
        type: boolean

permissions:
  contents: write

jobs:
  test_docsible:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Docsible (PR or latest)
        run: |
          if [[ "${{ github.event.inputs.use_latest }}" == "true" ]]; then
            echo "📦 Installing latest Docsible from main branch"
            pip install git+https://github.com/docsible/docsible.git@main
          elif [[ -n "${{ github.event.inputs.docsible_pr_number }}" ]]; then
            echo "📦 Installing Docsible from PR #${{ github.event.inputs.docsible_pr_number }}"
            pip install git+https://github.com/docsible/docsible.git@refs/pull/${{ github.event.inputs.docsible_pr_number }}/head
          else
            echo "❌ Please provide either a PR number or enable 'use_latest'."
            exit 1
          fi

      - name: Generate documentation for role
        run: |
          docsible -r ./ -g -o README.md -com -nob

      - name: Check for documentation changes
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --cached --exit-code; then
            echo "No changes to commit"
          elif [ -n "${TOKEN}" ]; then
            COMMIT_MSG="Automated doc update from Docsible "
            if [[ "${{ github.event.inputs.use_latest }}" == "true" ]]; then
              COMMIT_MSG+="(latest)"
            else
              COMMIT_MSG+="PR #${{ github.event.inputs.docsible_pr_number }}"
            fi
            git commit -m "${COMMIT_MSG}"
            git push "https://${TOKEN}@github.com/${{ github.repository }}.git" HEAD:main
          else
            echo "Skipping push: TOKEN is not set"
          fi
